name: PR Auto Draft Guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [main]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  contents: read
  checks: read
  statuses: read

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - name: Evaluate PR state
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const pull_number =
              context.payload.pull_request?.number ||
              context.payload.review?.pull_request_url?.split("/").pop();

            if (!pull_number) {
              console.log("No PR context found.");
              return;
            }

            const { data: fullPR } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number
            });

            if (fullPR.mergeable_state === "unknown") {
              console.log("Mergeable state not computed yet.");
              return;
            }

            let shouldDraft = false;

            // Merge conflicts
            if (fullPR.mergeable_state === "dirty") {
              shouldDraft = true;
            }

            // Not up to date with base branch
            if (fullPR.mergeable_state === "behind") {
              shouldDraft = true;
            }

            // Requested changes
            const { data: reviews } =
              await github.rest.pulls.listReviews({
                owner,
                repo,
                pull_number
              });

            const changesRequested = reviews.some(
              r => r.state === "CHANGES_REQUESTED"
            );

            if (changesRequested) {
              shouldDraft = true;
            }

            // Unresolved review threads
            const threadData = await github.graphql(`
              query($owner:String!, $repo:String!, $number:Int!) {
                repository(owner:$owner, name:$repo) {
                  pullRequest(number:$number) {
                    reviewThreads(first:100) {
                      nodes {
                        isResolved
                      }
                    }
                  }
                }
              }
            `, { owner, repo, number: parseInt(pull_number) });

            const unresolved =
              threadData.repository.pullRequest.reviewThreads.nodes
                .some(t => !t.isResolved);

            if (unresolved) {
              shouldDraft = true;
            }

            // CI / status checks
            const { data: combinedStatus } =
              await github.rest.repos.getCombinedStatusForRef({
                owner,
                repo,
                ref: fullPR.head.sha
              });

            if (combinedStatus.state === "failure") {
              shouldDraft = true;
            }

            // Apply state change
            if (shouldDraft && !fullPR.draft) {
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number,
                draft: true
              });
              console.log("Converted to Draft.");
            } 
            else if (!shouldDraft && fullPR.draft) {
              await github.rest.pulls.update({
                owner,
                repo,
                pull_number,
                draft: false
              });
              console.log("Marked Ready for Review.");
            } 
            else {
              console.log("No state change needed.");
            }
